baseURL: ""
languageCode: "en-us"
title: "Dippi"
theme: "PaperMod"

params: 
  cover: 
    linkFullImages: true

  homeInfoParams:
    Title: "Dippi Docs"
    Content: "To generate your API KEY you can register here https://client.dippi.xyz and create your project. If you want to give us feedback or leave any comments about our documentation or our products, you can do it here https://github.com/dippixyz/dippi-docs/issues/new"
    
  label:
    icon: "img/logo.png"

  socialIcons:
    - name: "github"
      url: "https://github.com/dippixyz"
    - name: "twitter"
      url: "https://twitter.com/dippixyz"
    - name: "website"
      url: "https://dippi.xyz"
    

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

menu: 
  main:
    - name: "Home"
      url: "/"
      weight: 10
